# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  minimalapi:
    image: minimalapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
